# Generated by Django 4.0.7 on 2022-11-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analyst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_analyst_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_user', models.CharField(max_length=50)),
                ('petrol', models.IntegerField(null=True)),
                ('diesel', models.IntegerField(null=True)),
                ('gas', models.IntegerField(null=True)),
                ('taxi', models.IntegerField(null=True)),
                ('localbus', models.IntegerField(null=True)),
                ('train', models.IntegerField(null=True)),
                ('lpg_cyclinder', models.IntegerField(null=True)),
                ('electricity', models.IntegerField(null=True)),
                ('Total_emission', models.IntegerField(null=True)),
                ('emission_calculate', models.BooleanField(default=False)),
            ],
        ),
    ]
