# Generated by Django 4.0.7 on 2022-12-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analyst', '0002_data_analyst_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_analyst_data',
            name='analyse',
            field=models.BooleanField(default=False),
        ),
    ]
