# Generated by Django 4.0.7 on 2022-12-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analyst', '0003_data_analyst_data_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_analyst_data',
            name='output',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
