# Generated by Django 4.0.7 on 2022-12-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analyst', '0004_data_analyst_data_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_analyst_data',
            name='output',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
