# Generated by Django 4.0.7 on 2022-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emission_calculate_industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol', models.IntegerField(null=True)),
                ('diesel', models.IntegerField(null=True)),
                ('gas', models.IntegerField(null=True)),
                ('electricity', models.IntegerField(null=True)),
                ('Total_emission', models.IntegerField(null=True)),
                ('emission_calculate', models.BooleanField(default=False)),
                ('send_to_analyse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='emission_checker_industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('Phone_number', models.PositiveBigIntegerField(null=True, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='indusdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('date', models.IntegerField(null=True)),
                ('people_working', models.IntegerField(null=True)),
                ('type_industry', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
