# Generated by Django 4.0.7 on 2022-12-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emission_checker_industry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='indusdata',
            new_name='indusdatail',
        ),
    ]
