# Generated by Django 4.0.7 on 2022-12-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emission_calculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol', models.IntegerField(null=True)),
                ('diesel', models.IntegerField(null=True)),
                ('gas', models.IntegerField(null=True)),
                ('taxi', models.IntegerField(null=True)),
                ('localbus', models.IntegerField(null=True)),
                ('train', models.IntegerField(null=True)),
                ('lpg_cyclinder', models.IntegerField(null=True)),
                ('electricity', models.IntegerField(null=True)),
                ('Total_emission', models.IntegerField(null=True)),
                ('emission_calculate', models.BooleanField(default=False)),
                ('send_to_analyse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='emission_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, null=True, unique=True)),
                ('Phone_number', models.PositiveBigIntegerField(null=True, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userdatail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('date', models.IntegerField(null=True)),
                ('no_of_peple', models.IntegerField(null=True)),
                ('type_of_shelter', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
